version: '3'
services:
  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: 0
    ports:
      - "5053:5050"
    volumes:
      - ${PWD}/projects:/app/projects
      # - ${PWD}/allure-results:/app/allure-results
      # - ${PWD}/allure-reports:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "https://allure.example.test"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5255:5252"
